# Generated by Django 6.0.6 on 2026-06-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affluence', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='affluence',
            new_name='affluence_a_niveau_15637b_idx',
            old_name='affluence_a_niveau_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='affluence',
            new_name='affluence_a_dernier_715007_idx',
            old_name='affluence_a_dernier_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='historiqueaffluence',
            new_name='affluence_h_agence__b53494_idx',
            old_name='affluence_h_agence__7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='historiqueaffluence',
            new_name='affluence_h_niveau_614114_idx',
            old_name='affluence_h_niveau_0j1k2l_idx',
        ),
    ]
