# Generated by Django 6.0.6 on 2026-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affluence', '0002_rename_affluence_a_niveau_1a2b3c_idx_affluence_a_niveau_15637b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affluence',
            name='niveau',
            field=models.CharField(choices=[('vert', 'Faible'), ('orange', 'Moyenne'), ('rouge', 'Forte')], db_index=True, default='vert', max_length=10, verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='historiqueaffluence',
            name='niveau',
            field=models.CharField(choices=[('vert', 'Faible'), ('orange', 'Moyenne'), ('rouge', 'Forte')], db_index=True, max_length=10, verbose_name='niveau'),
        ),
    ]
