# Generated by Django 6.0.6 on 2026-06-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agence',
            new_name='agencies_ag_statut_48a625_idx',
            old_name='agencies_ag_statut_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='agence',
            new_name='agencies_ag_code_923c76_idx',
            old_name='agencies_ag_code_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='agence',
            new_name='agencies_ag_latitud_f26ace_idx',
            old_name='agencies_ag_lat_lon_idx',
        ),
    ]
