# Generated by Django 6.0.6 on 2026-06-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='capteur',
            new_name='iot_capteur_esp32_i_1caa16_idx',
            old_name='iot_capteur_esp32_i_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='capteur',
            new_name='iot_capteur_type_dd1215_idx',
            old_name='iot_capteur_type_0j1k2l_idx',
        ),
        migrations.RenameIndex(
            model_name='esp32',
            new_name='iot_esp32_statut_0d5318_idx',
            old_name='iot_esp32_statut_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='esp32',
            new_name='iot_esp32_numero__7af086_idx',
            old_name='iot_esp32_numero__4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='passage',
            new_name='iot_passage_esp32_i_434842_idx',
            old_name='iot_passage_esp32_t_3m4n5o_idx',
        ),
        migrations.RenameIndex(
            model_name='passage',
            new_name='iot_passage_capteur_0a3d77_idx',
            old_name='iot_passage_capteur_6p7q8r_idx',
        ),
        migrations.RenameIndex(
            model_name='passage',
            new_name='iot_passage_directi_71d95b_idx',
            old_name='iot_passage_directi_9s0t1u_idx',
        ),
    ]
