"""
Données de peuplement RawMap — 20 agences à Kinshasa.

Coordonnées GPS approximatives par commune (WGS84).
"""

from datetime import time

from apps.agencies.models import JourSemaine, StatutAgence

SERVICES = [
    ('Retrait', 'Retrait d\'espèces en agence'),
    ('Dépôt', 'Dépôt d\'espèces et chèques'),
    ('Ouverture de compte', 'Ouverture de compte particulier et professionnel'),
    ('Crédit', 'Demandes et suivi de crédit'),
    ('Mobile Banking', 'Services bancaires mobiles Rawbank'),
]

JOURS_OUVERTURE = [
    JourSemaine.LUNDI,
    JourSemaine.MARDI,
    JourSemaine.MERCREDI,
    JourSemaine.JEUDI,
    JourSemaine.VENDREDI,
    JourSemaine.SAMEDI,
]

HEURES_SEMAINE = (time(8, 0), time(16, 0))
HEURES_SAMEDI = (time(8, 0), time(12, 0))

# personnes_presentes variées pour un mix VERT / ORANGE / ROUGE
AFFLUENCE_PERSONNES = [
    8, 12, 18, 22, 28,  # vert
    21, 26, 30, 35, 38,  # vert haut
    24, 32, 36, 42, 45,  # orange
    48, 52, 55, 58, 62,  # orange / rouge
]

AGENCES_KINSHASA = [
    {
        'code': 'RB-KIN-001',
        'nom': 'Agence Rawbank Gombe',
        'commune': 'Gombe',
        'adresse': '4 Avenue du Commerce',
        'latitude': -4.321700,
        'longitude': 15.322200,
        'capacite_max': 55,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010001',
    },
    {
        'code': 'RB-KIN-002',
        'nom': 'Agence Rawbank Lingwala',
        'commune': 'Lingwala',
        'adresse': '12 Avenue Kasa-Vubu',
        'latitude': -4.318900,
        'longitude': 15.304400,
        'capacite_max': 45,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010002',
    },
    {
        'code': 'RB-KIN-003',
        'nom': 'Agence Rawbank Barumbu',
        'commune': 'Barumbu',
        'adresse': '25 Avenue de la Libération',
        'latitude': -4.326700,
        'longitude': 15.312200,
        'capacite_max': 40,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010003',
    },
    {
        'code': 'RB-KIN-004',
        'nom': 'Agence Rawbank Kinshasa',
        'commune': 'Kinshasa',
        'adresse': '8 Boulevard du 30 Juin',
        'latitude': -4.331800,
        'longitude': 15.315000,
        'capacite_max': 50,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010004',
    },
    {
        'code': 'RB-KIN-005',
        'nom': 'Agence Rawbank Kintambo',
        'commune': 'Kintambo',
        'adresse': '17 Avenue de l\'Université',
        'latitude': -4.338900,
        'longitude': 15.291100,
        'capacite_max': 42,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010005',
    },
    {
        'code': 'RB-KIN-006',
        'nom': 'Agence Rawbank Ngaliema',
        'commune': 'Ngaliema',
        'adresse': '3 Avenue de la Justice',
        'latitude': -4.378900,
        'longitude': 15.258900,
        'capacite_max': 60,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010006',
    },
    {
        'code': 'RB-KIN-007',
        'nom': 'Agence Rawbank Bandalungwa',
        'commune': 'Bandalungwa',
        'adresse': '45 Avenue Bandalungwa',
        'latitude': -4.361100,
        'longitude': 15.288900,
        'capacite_max': 38,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010007',
    },
    {
        'code': 'RB-KIN-008',
        'nom': 'Agence Rawbank Kalamu',
        'commune': 'Kalamu',
        'adresse': '22 Avenue Kalamu',
        'latitude': -4.345600,
        'longitude': 15.301100,
        'capacite_max': 48,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010008',
    },
    {
        'code': 'RB-KIN-009',
        'nom': 'Agence Rawbank Limete',
        'commune': 'Limete',
        'adresse': '10 Route de Matadi',
        'latitude': -4.328900,
        'longitude': 15.351100,
        'capacite_max': 52,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010009',
    },
    {
        'code': 'RB-KIN-010',
        'nom': 'Agence Rawbank Matete',
        'commune': 'Matete',
        'adresse': '33 Avenue Matete',
        'latitude': -4.338900,
        'longitude': 15.365600,
        'capacite_max': 44,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010010',
    },
    {
        'code': 'RB-KIN-011',
        'nom': 'Agence Rawbank Lemba',
        'commune': 'Lemba',
        'adresse': '19 Avenue Lemba',
        'latitude': -4.378900,
        'longitude': 15.318900,
        'capacite_max': 46,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010011',
    },
    {
        'code': 'RB-KIN-012',
        'nom': 'Agence Rawbank Kisenso',
        'commune': 'Kisenso',
        'adresse': '7 Avenue Kisenso',
        'latitude': -4.391100,
        'longitude': 15.378900,
        'capacite_max': 35,
        'statut': StatutAgence.INACTIF,
        'telephone': '+243810010012',
    },
    {
        'code': 'RB-KIN-013',
        'nom': 'Agence Rawbank Masina',
        'commune': 'Masina',
        'adresse': '14 Avenue Masina',
        'latitude': -4.378900,
        'longitude': 15.391100,
        'capacite_max': 50,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010013',
    },
    {
        'code': 'RB-KIN-014',
        'nom': 'Agence Rawbank Kimbanseke',
        'commune': 'Kimbanseke',
        'adresse': '28 Avenue Kimbanseke',
        'latitude': -4.418900,
        'longitude': 15.401100,
        'capacite_max': 40,
        'statut': StatutAgence.INACTIF,
        'telephone': '+243810010014',
    },
    {
        'code': 'RB-KIN-015',
        'nom': 'Agence Rawbank Ndjili',
        'commune': 'Ndjili',
        'adresse': '5 Avenue Ndjili',
        'latitude': -4.401100,
        'longitude': 15.418900,
        'capacite_max': 42,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010015',
    },
    {
        'code': 'RB-KIN-016',
        'nom': 'Agence Rawbank Selembao',
        'commune': 'Selembao',
        'adresse': '11 Avenue Selembao',
        'latitude': -4.361100,
        'longitude': 15.258900,
        'capacite_max': 36,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010016',
    },
    {
        'code': 'RB-KIN-017',
        'nom': 'Agence Rawbank Bumbu',
        'commune': 'Bumbu',
        'adresse': '9 Avenue Bumbu',
        'latitude': -4.351100,
        'longitude': 15.281100,
        'capacite_max': 38,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010017',
    },
    {
        'code': 'RB-KIN-018',
        'nom': 'Agence Rawbank Makala',
        'commune': 'Makala',
        'adresse': '16 Avenue Makala',
        'latitude': -4.368900,
        'longitude': 15.271100,
        'capacite_max': 44,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010018',
    },
    {
        'code': 'RB-KIN-019',
        'nom': 'Agence Rawbank Mont Ngafula',
        'commune': 'Mont Ngafula',
        'adresse': '2 Route de Mont Ngafula',
        'latitude': -4.418900,
        'longitude': 15.271100,
        'capacite_max': 32,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010019',
    },
    {
        'code': 'RB-KIN-020',
        'nom': 'Agence Rawbank Ngaba',
        'commune': 'Ngaba',
        'adresse': '21 Avenue Ngaba',
        'latitude': -4.358900,
        'longitude': 15.308900,
        'capacite_max': 41,
        'statut': StatutAgence.ACTIF,
        'telephone': '+243810010020',
    },
]
