# Generated by Django 6.0.6 on 2026-06-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='atm',
            new_name='atm_atm_statut_4dabc6_idx',
            old_name='atm_atm_statut_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='atm',
            new_name='atm_atm_code_at_b95036_idx',
            old_name='atm_atm_code_at_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='atm',
            new_name='atm_atm_agence__751b76_idx',
            old_name='atm_atm_agence__7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='atm',
            new_name='atm_atm_latitud_55802b_idx',
            old_name='atm_atm_lat_lon_idx',
        ),
    ]
